### ISSUE TITLE
Wrong behavior

### ISSUE THREAD

**Issue by hannasorokina** [QumiQumi/sharp-optimize#1]
Output size after optimization is bigger then before.
![image](https://user-images.githubusercontent.com/41576056/209356872-0682b000-2f85-4773-8fd2-cccde99edb6d.png)

**Comment by QumiQumi** [comment]
Output image size depends on sharp settings - https://sharp.pixelplumbing.com/api-output. Sometimes processed images can be bigger size due to optimizing algorithms.
